
# Setup
title:               ChenZhongKai`s BLOG
tagline:             'Tomorrow is another day'
description:         'PHP'
url:                 http://wtgwtgwtg.github.io
baseurl:             
paginate:            5

# About/contact
author:
  name:              ChenZhongKai
  url:               http://wtgwtgwtg.github.io
  email:             wtg.czk@gmail.com

gems: [jekyll-paginate]
# Custom vars
version:             1.0.0
